crops = [
'Agave fibres',
'Almonds with shell',
'Anise, badian, fennel, and corian',
'Apples',
'Apricots',
'Arecanuts',
'Artichokes',
'Asparagus',
'Avocados',
'Bambara beans',
'Bananas',
'Barley',
'Beans dry',
'Beans green',
'Berries',
'Blueberries',
'Brazil nuts, with shell',
'Broad beans, horse beans, dry',
'Buckwheat',
'Cabbages and other brassicas',
'Canary seed',
'Carobs',
'Carrots and turnips',
'Cashew nuts with shell',
'Cashewapple',
'Cassava',
'Castor oil seed',
'Cauliflowers and broccoli',
'Cereals',
'Cherries',
'Chestnuts',
'Chick peas',
'Chicory roots',
'Chillies and peppers dry',
'Chillies and peppers green',
'Cinnamon (canella)',
'Citrus fruit',
'Cloves',
'Cocoa beans',
'Coconuts',
'Coffee,green',
'Coir',
'Cow peas,dry',
'Cranberries',
'Cucumbers and gherkins',
'Currants',
'Dates',
'Eggplants (aubergines)',
'Fibre Crops',
'Figs',
'Flax fibre and tow',
'Fonio',
'Forage products',
'Fruit fresh',
'Fruit, tropical fresh',
'Garlic',
'Ginger',
'Gooseberries',
'Grapefruit (incl. pomelos)',
'Grapes',
'Groundnuts, with shell',
'Hazelnuts, with shell',
'Hemp tow waste',
'Hempseed',
'Hops',
'Jute',
'Karite nuts (sheanuts)',
'Kiwi fruit',
'Kolanuts',
'Leeks,other alliaceous veg',
'Leguminous vegetables',
'Lemons and limes',
'Lentils',
'Lettuce and chicory',
'Linseed',
'Lupins',
'Maize',
'Maize, green',
'Mangoes, mangosteens, guavas',
'Manila fibre (Abaca)',
'Mate',
'Melonseed',
'Millet',
'Mixed grain',
'Mushrooms and truffles',
'Mustard seed',
'Natural rubber',
'Nutmeg,mace and cardamoms',
'Nuts',
'Oats',
'Oil palm fruit',
'Oilseeds',
'Okra',
'Olives',
'Onions (inc. shallots)',
'Onions, dry',
'Oranges',
'Other bastfibres',
'Other melons (incl. cantaloupes)',
'Papayas',
'Peaches and nectarines',
'Pears',
'Peas, dry',
'Peas, green',
'Pepper',
'Peppermint',
'Persimmons',
'Pigeon peas',
'Pineapples',
'Pistachios',
'Plantains',
'Plums and sloes',
'Popcorn',
'Poppy seed',
'Potatoes',
'Pulses',
'Pumpkins,squash and gourds',
'Pyrethrum dried',
'Quinces',
'Quinoa',
'Ramie',
'Rapeseed',
'Raspberries',
'Rice paddy',
'Roots and Tubers',
'Rye',
'Safflower seed',
'Seed cotton',
'Sesame seed',
'Sisal',
'Sorghum',
'Sour cherries',
'Soybeans',
'Spices',
'Spinach',
'Stone fruit',
'Strawberries',
'String beans',
'Sugar beet',
'Sugar cane',
'Sugar crops',
'Sunflower seed',
'Sweet potatoes',
'Tangerines, mandarins, and clementines',
'Taro (cocoyam)',
'Tea',
'Tobacco, unmanufactured',
'Tomatoes',
'Triticale',
'Tung nuts',
'Vanilla',
'Vegetables fresh',
'Vetches',
'Walnuts, with shell',
'Watermelons',
'Wheat',
'Yams',
'Yautia (cocoyam)']

