cropInputs = [
{'brand':'Generic','productName':'Organic fert', 'category':'Fertilizer','price':260,'units':'50 kilos','productIngredient':'','recommendedUsage':''},
{'brand':'Generic','productName':'Triple 14', 'category':'Fertilizer','price':1260,'units':'50 kilos','productIngredient':'','recommendedUsage':'5 after transplating'},
{'brand':'Yara','productName':'Viking', 'category':'Fertilizer','price':800,'units':'50 kilos','productIngredient':'','recommendedUsage':''},
{'brand':'Yara','productName':'46-0-0', 'category':'Fertilizer','price':600,'units':'50 kilos','productIngredient':'Nitrogen','recommendedUsage':'3 sacs/hectare'},
{'brand':'','productName':'Active gas', 'category':'Fuel','price':650,'units':'tank','productIngredient':'','recommendedUsage':'Cooking, etc'},
{'brand':'Shell','productName':'Gasoline', 'category':'Fuel','price':52.5,'units':'liter','productIngredient':'','recommendedUsage':'10 liters/day for hand tractor, 20 L/day for thresher'},
{'brand':'','productName':'Rogue', 'category':'Herbicide','price':560,'units':'liter','productIngredient':'','recommendedUsage':'Every 8-11 days, 1 liter per hectare'},
{'brand':'','productName':'Cynbus', 'category':'Insecticide','price':2000,'units':'pack','productIngredient':'','recommendedUsage':''},
{'brand':'','productName':'Puridan', 'category':'Insecticide','price':1400,'units':'pack','productIngredient':'','recommendedUsage':''},
{'brand':'','productName':'Visokill', 'category':'Insecticide','price':1860,'units':'pack','productIngredient':'','recommendedUsage':''},
{'brand':'Generic','productName':'Zinc phosphide', 'category':'Rat poison','price':240,'units':'pack','productIngredient':'','recommendedUsage':''},
{'brand':'IRRI','productName':'Certified Rice', 'category':'Seeds','price':1200,'units':'40 kilos','productIngredient':'','recommendedUsage':'80 kgs/hectare'},
{'brand':'IRRI','productName':'Hybrid rice seeds', 'category':'Seeds','price':1500,'units':'5 kilos','productIngredient':'','recommendedUsage':'20 kgs/hectare'},
{'brand':'Generic','productName':'Inbred rice seeds', 'category':'Seeds','price':680,'units':'40 kilos','productIngredient':'','recommendedUsage':'100 kgs/hectare'},
{'brand':'East-West','productName':'Mango seeds', 'category':'Seeds','price':1500,'units':'pack','productIngredient':'','recommendedUsage':''},
{'brand':'','productName':'Palay rice seeds', 'category':'Seeds','price':17,'units':'1 kilo','productIngredient':'','recommendedUsage':''},
{'brand':'East-West','productName':'Pomelo seeds', 'category':'Seeds','price':2500,'units':'pack','productIngredient':'','recommendedUsage':''},
{'brand':'East-West','productName':'Watermelon', 'category':'Seeds','price':3000,'units':'pack','productIngredient':'','recommendedUsage':''},
{'brand':'','productName':'2-4-D', 'category':'Weed killer','price':300,'units':'liter','productIngredient':'','recommendedUsage':'After 15 days of plantation or use it later on'},
{"brand":"Bayer","productName":"Act","productIngredient":"Mefenacet"},
{"brand":"Bayer","productName":"Actril","productIngredient":"Ioxynil"},
{"brand":"Bayer","productName":"Adengo (Corn)","productIngredient":"Thiencarbazone-methyl"},
{"brand":"Bayer","productName":"Adengo","productIngredient":"Isoxaflutole"},
{"brand":"Bayer","productName":"Admire","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Aeris","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Alanto","productIngredient":"Thiacloprid"},
{"brand":"Bayer","productName":"Aliette","productIngredient":"Fosetyl-Al"},
{"brand":"Bayer","productName":"Alion","productIngredient":"Indaziflam"},
{"brand":"Bayer","productName":"Alister","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Alister","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Alsystin","productIngredient":"Triflumuron"},
{"brand":"Bayer","productName":"Amigo","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Amparo","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Ancla","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Antracol","productIngredient":"Propineb"},
{"brand":"Bayer","productName":"Arcado","productIngredient":"Carpropamid"},
{"brand":"Bayer","productName":"Archipel","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Arena C","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Arkan","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Arozin","productIngredient":"Anilofos"},
{"brand":"Bayer","productName":"Artemis","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Artist","productIngredient":"Flufenacet"},
{"brand":"Bayer","productName":"Asket","productIngredient":"Phenmedipham"},
{"brand":"Bayer","productName":"Atento","productIngredient":"Fluquinconazole"},
{"brand":"Bayer","productName":"Atlantis","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Attribut","productIngredient":"Propoxycarbazone-Sodium"},
{"brand":"Bayer","productName":"Audax","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Autumn","productIngredient":"Iodosulfuron"},
{"brand":"Bayer","productName":"Auxo","productIngredient":"Tembotrione"},
{"brand":"Bayer","productName":"Aviator Xpro","productIngredient":"Bixafen "},
{"brand":"Bayer","productName":"Axiom","productIngredient":"Flufenacet"},
{"brand":"Bayer","productName":"Azur","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Bacara","productIngredient":"Flurtamone "},
{"brand":"Bayer","productName":"Baghera","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Balance","productIngredient":"Isoxaflutole"},
{"brand":"Bayer","productName":"Bandur1","productIngredient":"Aclonifen"},
{"brand":"Bayer","productName":"Bariard","productIngredient":"Thiacloprid"},
{"brand":"Bayer","productName":"Bariton","productIngredient":"Fluoxastrobin"},
{"brand":"Bayer","productName":"Basta","productIngredient":"Glufosinate-ammonium [non-selective usage]"},
{"brand":"Bayer","productName":"Batl","productIngredient":"Mefenacet"},
{"brand":"Bayer","productName":"Baycid","productIngredient":"Fenthion"},
{"brand":"Bayer","productName":"Baycoral","productIngredient":"Bitertanol"},
{"brand":"Bayer","productName":"Baycor","productIngredient":"Bitertanol"},
{"brand":"Bayer","productName":"Bayfidan","productIngredient":"Triadimenol"},
{"brand":"Bayer","productName":"Bayleton","productIngredient":"Triadimefon"},
{"brand":"Bayer","productName":"Baysiston","productIngredient":"Triadimenol"},
{"brand":"Bayer","productName":"Baytan","productIngredient":"Triadimenol"},
{"brand":"Bayer","productName":"Baythroid XL","productIngredient":"Betacyfluthrin"},
{"brand":"Bayer","productName":"Becano","productIngredient":"Indaziflam"},
{"brand":"Bayer","productName":"Belt","productIngredient":"Flubendiamide"},
{"brand":"Bayer","productName":"Betamix","productIngredient":"Desmedipham"},
{"brand":"Bayer","productName":"Betanal AM 22","productIngredient":"Desmedipham"},
{"brand":"Bayer","productName":"Betanal Quattro","productIngredient":"Ethofumesate"},
{"brand":"Bayer","productName":"Betanal","productIngredient":"Phenmedipham"},
{"brand":"Bayer","productName":"Betanalexpert/elite","productIngredient":"Ethofumesate"},
{"brand":"Bayer","productName":"Betanex","productIngredient":"Desmedipham"},
{"brand":"Bayer","productName":"Biscaya","productIngredient":"Thiacloprid"},
{"brand":"Bayer","productName":"Blindage","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Boreal","productIngredient":"Isoxaflutole"},
{"brand":"Bayer","productName":"Brodal","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Bronate Advanced","productIngredient":"Bromoxynil"},
{"brand":"Bayer","productName":"Buctril M","productIngredient":"Bromoxynil"},
{"brand":"Bayer","productName":"Buctril","productIngredient":"Bromoxynil"},
{"brand":"Bayer","productName":"Bulldock","productIngredient":"Betacyfluthrin"},
{"brand":"Bayer","productName":"Bullstar","productIngredient":"Betacyfluthrin"},
{"brand":"Bayer","productName":"Caddy","productIngredient":"Cyproconazole"},
{"brand":"Bayer","productName":"CaddyArbo","productIngredient":"Cyproconazole"},
{"brand":"Bayer","productName":"Cadou","productIngredient":"Flufenacet"},
{"brand":"Bayer","productName":"CaLypso","productIngredient":"Thiacloprid"},
{"brand":"Bayer","productName":"Camposan1","productIngredient":"Ethephon"},
{"brand":"Bayer","productName":"Capture","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Carat","productIngredient":"Flurtamone "},
{"brand":"Bayer","productName":"Carioca","productIngredient":"Aclonifen"},
{"brand":"Bayer","productName":"Carioca","productIngredient":"Oxadiargyl"},
{"brand":"Bayer","productName":"Censor","productIngredient":"Fenamidone"},
{"brand":"Bayer","productName":"Cerenturf","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Cerone","productIngredient":"Ethephon"},
{"brand":"Bayer","productName":"Certero","productIngredient":"Triflumuron"},
{"brand":"Bayer","productName":"Certop","productIngredient":"Filmcoating"},
{"brand":"Bayer","productName":"Challenge","productIngredient":"Aclonifen"},
{"brand":"Bayer","productName":"Cheetah","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Chekker","productIngredient":"Iodosulfuron"},
{"brand":"Bayer","productName":"Chevalier","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Chinook","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Clarinet","productIngredient":"Pyrimethanil"},
{"brand":"Bayer","productName":"Confidor Energy","productIngredient":"Deltamethrin"},
{"brand":"Bayer","productName":"Confidor O-teq","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Confidor","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Connect","productIngredient":"Betacyfluthrin"},
{"brand":"Bayer","productName":"Connect","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Consento","productIngredient":"Fenamidone"},
{"brand":"Bayer","productName":"Consento","productIngredient":"Propamocarb HCl"},
{"brand":"Bayer","productName":"Corvus (Corn)","productIngredient":"Thiencarbazone-methyl"},
{"brand":"Bayer","productName":"Corvus","productIngredient":"Isoxaflutole"},
{"brand":"Bayer","productName":"Cossack","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Cougar","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"CropStar","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Curbix","productIngredient":"Ethiprole"},
{"brand":"Bayer","productName":"Daniemon (in japanese characters)","productIngredient":"Spirodiclofen"},
{"brand":"Bayer","productName":"Datif G","productIngredient":"Filmcoating"},
{"brand":"Bayer","productName":"Decis","productIngredient":"Deltamethrin"},
{"brand":"Bayer","productName":"Define","productIngredient":"Flufenacet"},
{"brand":"Bayer","productName":"Def","productIngredient":"Tribufos"},
{"brand":"Bayer","productName":"Delaro","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Delcut","productIngredient":"Oxadiazon"},
{"brand":"Bayer","productName":"Derosal Plus","productIngredient":"Carbendazim"},
{"brand":"Bayer","productName":"Derosal","productIngredient":"Carbendazim"},
{"brand":"Bayer","productName":"Derosal","productIngredient":"Carbendazim"},
{"brand":"Bayer","productName":"Diplome","productIngredient":"Metosulam"},
{"brand":"Bayer","productName":"Dopler","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Doublestar","productIngredient":"Fentrazamide"},
{"brand":"Bayer","productName":"Draza","productIngredient":"Methiocarb"},
{"brand":"Bayer","productName":"Dropp Ultra1","productIngredient":"Thidiazuron"},
{"brand":"Bayer","productName":"Dropp SC","productIngredient":"Thidiazuron"},
{"brand":"Bayer","productName":"Dropp Ultra","productIngredient":"Thidiazuron"},
{"brand":"Bayer","productName":"Dropp","productIngredient":"Thidiazuron"},
{"brand":"Bayer","productName":"Eagle","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Eclipse","productIngredient":"Metosulam"},
{"brand":"Bayer","productName":"efa","productIngredient":"Fluoxastrobin"},
{"brand":"Bayer","productName":"El Hombre","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Elite","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Envidor","productIngredient":"Spirodiclofen"},
{"brand":"Bayer","productName":"Equip","productIngredient":"Foramsulfuron"},
{"brand":"Bayer","productName":"Escocet","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Estalion","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Ethrel","productIngredient":"Ethephon"},
{"brand":"Bayer","productName":"Evidence","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Exact","productIngredient":"Triadimenol"},
{"brand":"Bayer","productName":"Faibel","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Falcon","productIngredient":"Spiroxamine"},
{"brand":"Bayer","productName":"Falcon","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Fandango","productIngredient":"Fluoxastrobin "},
{"brand":"Bayer","productName":"FandangoS","productIngredient":"Fluoxastrobin "},
{"brand":"Bayer","productName":"Fenikan","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Fenix","productIngredient":"Aclonifen"},
{"brand":"Bayer","productName":"Fenomenal","productIngredient":"Fenamidone"},
{"brand":"Bayer","productName":"Finale","productIngredient":"Glufosinate-ammonium [non-selective usage]"},
{"brand":"Bayer","productName":"Finish 6 Pro","productIngredient":"Ethephon"},
{"brand":"Bayer","productName":"Finish","productIngredient":"Ethephon"},
{"brand":"Bayer","productName":"First","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Fitoraz","productIngredient":"Propineb"},
{"brand":"Bayer","productName":"Flint","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Folicur","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Furore","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Futur","productIngredient":"Thiodicarb"},
{"brand":"Bayer","productName":"Galahad","productIngredient":"Ethofumesate"},
{"brand":"Bayer","productName":"Galmano Plus","productIngredient":"Fluquinconazole"},
{"brand":"Bayer","productName":"Galmano","productIngredient":"Fluquinconazole"},
{"brand":"Bayer","productName":"Gaucho MT","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Gaucho MZ","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Gaucho Primo","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Gaucho XT","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Gaucho","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Ginstar","productIngredient":"Thidiazuron"},
{"brand":"Bayer","productName":"Gladium","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Gratil","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Grazie","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Grodyl","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Harpo Z","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Herold","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Hero","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Hinochloa","productIngredient":"Mefenacet"},
{"brand":"Bayer","productName":"Hoegrass","productIngredient":"Diclofop-methyl"},
{"brand":"Bayer","productName":"Hoelon","productIngredient":"Diclofop-methyl"},
{"brand":"Bayer","productName":"Hoestar","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Horizon","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Huskie","productIngredient":"Pyrasulfotole"},
{"brand":"Bayer","productName":"Hussar Evolution","productIngredient":"Iodosulfuron"},
{"brand":"Bayer","productName":"Hussar maxx","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Hussar OF","productIngredient":"Iodosulfuron"},
{"brand":"Bayer","productName":"Hussar","productIngredient":"Iodosulfuron"},
{"brand":"Bayer","productName":"Huzar Activ","productIngredient":"Iodosulfuron"},
{"brand":"Bayer","productName":"Illoxan","productIngredient":"Diclofop-methyl"},
{"brand":"Bayer","productName":"Iloxan)","productIngredient":"Diclofop-methyl"},
{"brand":"Bayer","productName":"Imochi Ace Kirappu","productIngredient":"Metominostrobin"},
{"brand":"Bayer","productName":"Imochi Ace Starkle","productIngredient":"Metominostrobin"},
{"brand":"Bayer","productName":"Imochi Ace","productIngredient":"Metominostrobin"},
{"brand":"Bayer","productName":"Imprimo","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Impulse","productIngredient":"Spiroxamine"},
{"brand":"Bayer","productName":"Infinito","productIngredient":"Fluopicolide"},
{"brand":"Bayer","productName":"Infinito","productIngredient":"Propamocarb HCl"},
{"brand":"Bayer","productName":"Infinity","productIngredient":"Pyrasulfotole"},
{"brand":"Bayer","productName":"Innova DX","productIngredient":"Fentrazamide"},
{"brand":"Bayer","productName":"Innova","productIngredient":"Fentrazamide"},
{"brand":"Bayer","productName":"Input Set","productIngredient":"Spiroxamine"},
{"brand":"Bayer","productName":"Input","productIngredient":"Prothioconazole "},
{"brand":"Bayer","productName":"Invento","productIngredient":"Iprovalicarb"},
{"brand":"Bayer","productName":"Jaunt","productIngredient":"Fluoxastrobin "},
{"brand":"Bayer","productName":"Javelin","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Jockey","productIngredient":"Fluquinconazole"},
{"brand":"Bayer","productName":"Justmeet","productIngredient":"Fenhexamid"},
{"brand":"Bayer","productName":"Kemifam Flow","productIngredient":"Phenmedipham"},
{"brand":"Bayer","productName":"Kendo","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Kirappu","productIngredient":"Ethiprole"},
{"brand":"Bayer","productName":"Lagon","productIngredient":"Isoxaflutole"},
{"brand":"Bayer","productName":"Lamardor","productIngredient":"Prothioconazole"},
{"brand":"Bayer","productName":"Larvin","productIngredient":"Thiodicarb"},
{"brand":"Bayer","productName":"Laudis","productIngredient":"Tembotrione"},
{"brand":"Bayer","productName":"Laureat","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Lazulie","productIngredient":"Fenhexamid"},
{"brand":"Bayer","productName":"Lebaycid","productIngredient":"Fenthion"},
{"brand":"Bayer","productName":"Lecspro","productIngredient":"Fentrazamide"},
{"brand":"Bayer","productName":"Lecs","productIngredient":"Fentrazamide"},
{"brand":"Bayer","productName":"Legion","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Leverage","productIngredient":"Betacyfluthrin"},
{"brand":"Bayer","productName":"Liberator","productIngredient":"Flufenacet"},
{"brand":"Bayer","productName":"Liberty","productIngredient":"Glufosinate-ammonium [selective usage]"},
{"brand":"Bayer","productName":"Longshot","productIngredient":"Benfuresate"},
{"brand":"Bayer","productName":"Longshot","productIngredient":"Oxadiazon"},
{"brand":"Bayer","productName":"Madison","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Maedusi","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Magic Tandem","productIngredient":"Ethofumesate"},
{"brand":"Bayer","productName":"Magma","productIngredient":"Mefenacet"},
{"brand":"Bayer","productName":"MaisTer","productIngredient":"Foramsulfuron"},
{"brand":"Bayer","productName":"Mandore","productIngredient":"Iprovalicarb"},
{"brand":"Bayer","productName":"Matador","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Melody Care/Combi/Compact/Duo/Med/Trio","productIngredient":"Iprovalicarb"},
{"brand":"Bayer","productName":"Merlin","productIngredient":"Isoxaflutole"},
{"brand":"Bayer","productName":"Mesurol Pro","productIngredient":"Methiocarb"},
{"brand":"Bayer","productName":"Mesurol","productIngredient":"Methiocarb"},
{"brand":"Bayer","productName":"Mesurol","productIngredient":"Methiocarb"},
{"brand":"Bayer","productName":"Mikado","productIngredient":"Sulcotrione"},
{"brand":"Bayer","productName":"Mikal","productIngredient":"Fosetyl-Al"},
{"brand":"Bayer","productName":"Mildex","productIngredient":"Fenamidone"},
{"brand":"Bayer","productName":"Milord","productIngredient":"Spiroxamine"},
{"brand":"Bayer","productName":"Milraz","productIngredient":"Propineb"},
{"brand":"Bayer","productName":"Milrod","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Monarca","productIngredient":"Thiacloprid"},
{"brand":"Bayer","productName":"Monceren Pro","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Moncerenrunner","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Monceren G","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Monceren GT","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Monceren","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Monceren","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Montur","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Movento","productIngredient":"Spirotetramat"},
{"brand":"Bayer","productName":"Muralla","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Mythos","productIngredient":"Pyrimethanil"},
{"brand":"Bayer","productName":"Nativo","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Nativo","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Nikeyl","productIngredient":"Aclonifen"},
{"brand":"Bayer","productName":"Nominee","productIngredient":"Bispyribac-sodium"},
{"brand":"Bayer","productName":"Nortron","productIngredient":"Ethofumesate"},
{"brand":"Bayer","productName":"Oberon","productIngredient":"Spiromesifen"},
{"brand":"Bayer","productName":"Ocarina","productIngredient":"Iprovalicarb"},
{"brand":"Bayer","productName":"Octave","productIngredient":"Prochloraz"},
{"brand":"Bayer","productName":"Odena","productIngredient":"Iprovalicarb"},
{"brand":"Bayer","productName":"Olympus","productIngredient":"Propoxycarbazone-Sodium"},
{"brand":"Bayer","productName":"OlympusFlex)","productIngredient":"Propoxycarbazone-Sodium"},
{"brand":"Bayer","productName":"Omega","productIngredient":"Prochloraz"},
{"brand":"Bayer","productName":"OnlyOne","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Option","productIngredient":"Foramsulfuron"},
{"brand":"Bayer","productName":"Oribright","productIngredient":"Metominostrobin"},
{"brand":"Bayer","productName":"Osprey","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Othello","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Oxytril","productIngredient":"Bromoxynil"},
{"brand":"Bayer","productName":"Pacifica","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Panther","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Pardner","productIngredient":"Bromoxynil"},
{"brand":"Bayer","productName":"Password","productIngredient":"Fenhexamid"},
{"brand":"Bayer","productName":"Peridiam","productIngredient":"Filmcoating"},
{"brand":"Bayer","productName":"Podium S","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Poncho","productIngredient":"Clothianidin"},
{"brand":"Bayer","productName":"PonchoBeta","productIngredient":"Clothianidin"},
{"brand":"Bayer","productName":"PositronDuo","productIngredient":"Iprovalicarb"},
{"brand":"Bayer","productName":"Precept and Wolverine","productIngredient":"Pyrasulfotole"},
{"brand":"Bayer","productName":"Prep","productIngredient":"Ethephon"},
{"brand":"Bayer","productName":"Prestige","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Prestige","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Previcur N","productIngredient":"Propamocarb HCl"},
{"brand":"Bayer","productName":"Previcur Energy","productIngredient":"Propamocarb HCl"},
{"brand":"Bayer","productName":"Proclaim","productIngredient":"Bitertanol"},
{"brand":"Bayer","productName":"Prodigio","productIngredient":"Aclonifen"},
{"brand":"Bayer","productName":"Profiler","productIngredient":"Fluopicolide"},
{"brand":"Bayer","productName":"Profiler","productIngredient":"Fosetyl-Al"},
{"brand":"Bayer","productName":"Proline","productIngredient":"Prothioconazole "},
{"brand":"Bayer","productName":"Pronto Plus","productIngredient":"Spiroxamine"},
{"brand":"Bayer","productName":"ProntoPlus","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Prosaro","productIngredient":"Prothioconazole "},
{"brand":"Bayer","productName":"Prosaro","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Proseed","productIngredient":"Prothioconazole"},
{"brand":"Bayer","productName":"Prosper","productIngredient":"Clothianidin"},
{"brand":"Bayer","productName":"Prosper","productIngredient":"Spiroxamine"},
{"brand":"Bayer","productName":"Proteus","productIngredient":"Deltamethrin"},
{"brand":"Bayer","productName":"Proteus","productIngredient":"Thiacloprid"},
{"brand":"Bayer","productName":"Provado","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Provence","productIngredient":"Isoxaflutole"},
{"brand":"Bayer","productName":"Provost","productIngredient":"Prothioconazole "},
{"brand":"Bayer","productName":"Pulstop","productIngredient":"Fentrazamide"},
{"brand":"Bayer","productName":"Puma Super","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Quartz GT","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Quartz S","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Quartz Super","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"R6 Albis","productIngredient":"Fosetyl-Al"},
{"brand":"Bayer","productName":"R6 Trevi","productIngredient":"Fosetyl-Al"},
{"brand":"Bayer","productName":"Radius","productIngredient":"Flufenacet"},
{"brand":"Bayer","productName":"Raft","productIngredient":"Oxadiargyl"},
{"brand":"Bayer","productName":"Ralon Super","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Rancho","productIngredient":"Mefenacet"},
{"brand":"Bayer","productName":"Rasantan","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Raxil Extra","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Raxil T","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Raxil","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Reason","productIngredient":"Fenamidone"},
{"brand":"Bayer","productName":"Redigo","productIngredient":"Prothioconazole"},
{"brand":"Bayer","productName":"Rely","productIngredient":"Glufosinate-ammonium [non-selective usage]"},
{"brand":"Bayer","productName":"Revent","productIngredient":"Thidiazuron"},
{"brand":"Bayer","productName":"Rhizofilm","productIngredient":"Filmcoating"},
{"brand":"Bayer","productName":"Rhodax","productIngredient":"Fosetyl-Al"},
{"brand":"Bayer","productName":"Ricestar Xtra","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Ricestar","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Rimfire Max","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Ronstar D Flo","productIngredient":"Oxadiazon"},
{"brand":"Bayer","productName":"Ronstar PL","productIngredient":"Oxadiazon"},
{"brand":"Bayer","productName":"Ronstar","productIngredient":"Oxadiazon"},
{"brand":"Bayer","productName":"Routine","productIngredient":"Isotianil"},
{"brand":"Bayer","productName":"Rovral","productIngredient":"Iprodione"},
{"brand":"Bayer","productName":"Rumpas","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Scala","productIngredient":"Pyrimethanil"},
{"brand":"Bayer","productName":"Scenic","productIngredient":"Fluoxastrobin"},
{"brand":"Bayer","productName":"Sekator","productIngredient":"Iodosulfuron"},
{"brand":"Bayer","productName":"Semevin","productIngredient":"Thiodicarb"},
{"brand":"Bayer","productName":"Sencoral Sencorex","productIngredient":"Metribuzin"},
{"brand":"Bayer","productName":"Sencor","productIngredient":"Metribuzin"},
{"brand":"Bayer","productName":"Sevin XLR Plus","productIngredient":"Carbaryl"},
{"brand":"Bayer","productName":"Sevin","productIngredient":"Carbaryl"},
{"brand":"Bayer","productName":"Siganex","productIngredient":"Pyrimethanil"},
{"brand":"Bayer","productName":"Sigma","productIngredient":"Mesosulfuron-methyl"},
{"brand":"Bayer","productName":"Silvacur","productIngredient":"Tebuconazole"},
{"brand":"Bayer","productName":"Sirbel","productIngredient":"Iprovalicarb"},
{"brand":"Bayer","productName":"Skol","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Skyway Xpro","productIngredient":"Bixafen "},
{"brand":"Bayer","productName":"Soberan","productIngredient":"Tembotrione"},
{"brand":"Bayer","productName":"Solomon","productIngredient":"Betacyfluthrin"},
{"brand":"Bayer","productName":"Specticle","productIngredient":"Indaziflam"},
{"brand":"Bayer","productName":"Sphere","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Sporgon","productIngredient":"Prochloraz"},
{"brand":"Bayer","productName":"Sportak","productIngredient":"Prochloraz"},
{"brand":"Bayer","productName":"Squire","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Stallion","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Stance SC","productIngredient":"Cyclanilide"},
{"brand":"Bayer","productName":"Starice","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Stratego","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Sunrice","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Sunstar","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Tega","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Teldor Combi","productIngredient":"Fenhexamid"},
{"brand":"Bayer","productName":"Teldor","productIngredient":"Fenhexamid"},
{"brand":"Bayer","productName":"Terano","productIngredient":"Flufenacet"},
{"brand":"Bayer","productName":"Terano","productIngredient":"Metosulam"},
{"brand":"Bayer","productName":"Thumper","productIngredient":"Bromoxynil"},
{"brand":"Bayer","productName":"Thunder O-teq","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Tiara","productIngredient":"Flufenacet"},
{"brand":"Bayer","productName":"Tie Break","productIngredient":"Fenhexamid"},
{"brand":"Bayer","productName":"Tigrex","productIngredient":"Diflufenican"},
{"brand":"Bayer","productName":"Tihan (cotton in West Africa)","productIngredient":"Spirotetramat"},
{"brand":"Bayer","productName":"Tiller Gold","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Tiller","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Tiller","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Tilmor","productIngredient":"Prothioconazole "},
{"brand":"Bayer","productName":"Topstar","productIngredient":"Oxadiargyl"},
{"brand":"Bayer","productName":"Totril","productIngredient":"Ioxynil"},
{"brand":"Bayer","productName":"Tramat","productIngredient":"Ethofumesate"},
{"brand":"Bayer","productName":"Trilex","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Trivia","productIngredient":"Fluopicolide"},
{"brand":"Bayer","productName":"Trotis","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Tundra","productIngredient":"Pyrasulfotole"},
{"brand":"Bayer","productName":"Turbo","productIngredient":"Betacyfluthrin"},
{"brand":"Bayer","productName":"Turbo","productIngredient":"Ethoxysulfuron"},
{"brand":"Bayer","productName":"Turfsiba","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Twist","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"Ultari","productIngredient":"Pencycuron"},
{"brand":"Bayer","productName":"Ultor (second market USA)","productIngredient":"Spirotetramat"},
{"brand":"Bayer","productName":"Valiant","productIngredient":"Fosetyl-Al"},
{"brand":"Bayer","productName":"Velocity M3","productIngredient":"Pyrasulfotole"},
{"brand":"Bayer","productName":"Velocity (Cereals)","productIngredient":"Thiencarbazone-methyl"},
{"brand":"Bayer","productName":"Velocity","productIngredient":"Pyrasulfotole"},
{"brand":"Bayer","productName":"Verita","productIngredient":"Fenamidone"},
{"brand":"Bayer","productName":"Vigold","productIngredient":"Fluoxastrobin "},
{"brand":"Bayer","productName":"Vision","productIngredient":"Pyrimethanil"},
{"brand":"Bayer","productName":"Volare","productIngredient":"Fluopicolide"},
{"brand":"Bayer","productName":"Votivo; Poncho/Votivo","productIngredient":"Bacillus firmus"},
{"brand":"Bayer","productName":"Walabi","productIngredient":"Pyrimethanil"},
{"brand":"Bayer","productName":"Whip","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"Wildcat","productIngredient":"Fenoxaprop-P-ethyl"},
{"brand":"Bayer","productName":"WinAdmire","productIngredient":"Carpropamid"},
{"brand":"Bayer","productName":"WinAdmireGreatam","productIngredient":"Carpropamid"},
{"brand":"Bayer","productName":"Win","productIngredient":"Carpropamid"},
{"brand":"Bayer","productName":"WinBariard","productIngredient":"Carpropamid"},
{"brand":"Bayer","productName":"WinGazzet","productIngredient":"Carpropamid"},
{"brand":"Bayer","productName":"Wolface","productIngredient":"Mefenacet"},
{"brand":"Bayer","productName":"Yorel","productIngredient":"Iprovalicarb"},
{"brand":"Bayer","productName":"Yunta","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Zantara","productIngredient":"Bixafen "},
{"brand":"Bayer","productName":"Zark","productIngredient":"Mefenacet"},
{"brand":"Bayer","productName":"Zato","productIngredient":"Trifloxystrobin"},
{"brand":"Bayer","productName":"ZorroFS 236,3","productIngredient":"Imidacloprid"},
{"brand":"Bayer","productName":"Adret","productIngredient":"Amidosulfuron"},
{"brand":"Bayer","productName":"Decision","productIngredient":"Diclofop-methyl"},
{"brand":"Monsanto","productName":"AquaMaster","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Asgrow","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Bullet","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Certainty Turf","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Channel","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Degree XTRA","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"DEKALB","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Deltapine","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Fielder's Choice Direct","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Fontanelle","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Gold Country Seed","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Hubner Seed","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"INTRRO","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Jung Seed Genetics","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Kruger Seeds","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Lariat","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Lewis Hybrids","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Micro-Tech","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Outrider","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Rea Hybrids","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Roundup PowerMAX","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Roundup PRO Concentrate","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Roundup PROMAX","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Roundup QuikPRO","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Roundup WeatherMAX","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"RT 3","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Specialty Hybrids","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Stewart Seeds","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Stone Seed Group","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"Trelay Seeds","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"TripleFLEX","productIngredient":"Unknown"},
{"brand":"Monsanto","productName":"WestBred","productIngredient":"Unknown"}]


inputIngredients = {"Bayer":[
{"ingredient":"Aclonifen","category":"Herbicides"},
{"ingredient":"Amidosulfuron","category":"Herbicides"},
{"ingredient":"Anilofos","category":"Herbicides"},
{"ingredient":"Bacillus firmus","category":"Seed Treatment"},
{"ingredient":"Benfuresate","category":"Herbicides"},
{"ingredient":"Betacyfluthrin","category":"Insecticides"},
{"ingredient":"Bispyribac-sodium","category":"Herbicides"},
{"ingredient":"Bitertanol","category":"Fungicides"},
{"ingredient":"Bixafen ","category":"Fungicides"},
{"ingredient":"Bromoxynil","category":"Herbicides"},
{"ingredient":"Carbaryl","category":"Insecticides"},
{"ingredient":"Carbendazim","category":"Fungicides"},
{"ingredient":"Carbendazim","category":"Seed Treatment"},
{"ingredient":"Carpropamid","category":"Fungicides"},
{"ingredient":"Clothianidin","category":"Seed Treatment"},
{"ingredient":"Cyclanilide","category":"Plant Growth Regulators"},
{"ingredient":"Cyproconazole","category":"Fungicides"},
{"ingredient":"Deltamethrin","category":"Insecticides"},
{"ingredient":"Desmedipham","category":"Herbicides"},
{"ingredient":"Diclofop-methyl","category":"Herbicides"},
{"ingredient":"Diflufenican","category":"Herbicides"},
{"ingredient":"Ethephon","category":"Plant Growth Regulators"},
{"ingredient":"Ethiprole","category":"Insecticides"},
{"ingredient":"Ethofumesate","category":"Herbicides"},
{"ingredient":"Ethoxysulfuron","category":"Herbicides"},
{"ingredient":"Fenamidone","category":"Fungicides"},
{"ingredient":"Fenhexamid","category":"Fungicides"},
{"ingredient":"Fenoxaprop-P-ethyl","category":"Herbicides"},
{"ingredient":"Fenthion","category":"Insecticides"},
{"ingredient":"Fentrazamide","category":"Herbicides"},
{"ingredient":"Filmcoating","category":"Seed Treatment"},
{"ingredient":"Flubendiamide","category":"Insecticides"},
{"ingredient":"Flufenacet","category":"Herbicides"},
{"ingredient":"Fluopicolide","category":"Fungicides"},
{"ingredient":"Fluoxastrobin ","category":"Fungicides"},
{"ingredient":"Fluoxastrobin","category":"Seed Treatment"},
{"ingredient":"Fluquinconazole","category":"Seed Treatment"},
{"ingredient":"Flurtamone ","category":"Herbicides"},
{"ingredient":"Foramsulfuron","category":"Herbicides"},
{"ingredient":"Fosetyl-Al","category":"Fungicides"},
{"ingredient":"Glufosinate-ammonium [non-selective usage]","category":"Herbicides"},
{"ingredient":"Glufosinate-ammonium [selective usage]","category":"Herbicides"},
{"ingredient":"Imidacloprid","category":"Insecticides"},
{"ingredient":"Imidacloprid","category":"Seed Treatment"},
{"ingredient":"Indaziflam","category":"Herbicides"},
{"ingredient":"Iodosulfuron","category":"Herbicides"},
{"ingredient":"Ioxynil","category":"Herbicides"},
{"ingredient":"Iprodione","category":"Fungicides"},
{"ingredient":"Iprovalicarb","category":"Fungicides"},
{"ingredient":"Isotianil","category":"Fungicides"},
{"ingredient":"Isoxaflutole","category":"Herbicides"},
{"ingredient":"Mefenacet","category":"Herbicides"},
{"ingredient":"Mesosulfuron-methyl","category":"Herbicides"},
{"ingredient":"Methiocarb","category":"Insecticides"},
{"ingredient":"Methiocarb","category":"Seed Treatment"},
{"ingredient":"Metominostrobin","category":"Fungicides"},
{"ingredient":"Metosulam","category":"Herbicides"},
{"ingredient":"Metribuzin","category":"Herbicides"},
{"ingredient":"Oxadiargyl","category":"Herbicides"},
{"ingredient":"Oxadiazon","category":"Herbicides"},
{"ingredient":"Pencycuron","category":"Fungicides"},
{"ingredient":"Pencycuron","category":"Seed Treatment"},
{"ingredient":"Phenmedipham","category":"Herbicides"},
{"ingredient":"Prochloraz","category":"Fungicides"},
{"ingredient":"Propamocarb HCl","category":"Fungicides"},
{"ingredient":"Propineb","category":"Fungicides"},
{"ingredient":"Propoxycarbazone-Sodium","category":"Herbicides"},
{"ingredient":"Prothioconazole ","category":"Fungicides"},
{"ingredient":"Prothioconazole","category":"Seed Treatment"},
{"ingredient":"Pyrasulfotole","category":"Herbicides"},
{"ingredient":"Pyrimethanil","category":"Fungicides"},
{"ingredient":"Spirodiclofen","category":"Insecticides"},
{"ingredient":"Spiromesifen","category":"Insecticides"},
{"ingredient":"Spirotetramat","category":"Insecticides"},
{"ingredient":"Spiroxamine","category":"Fungicides"},
{"ingredient":"Sulcotrione","category":"Herbicides"},
{"ingredient":"Tebuconazole","category":"Fungicides"},
{"ingredient":"Tebuconazole","category":"Seed Treatment"},
{"ingredient":"Tembotrione","category":"Herbicides"},
{"ingredient":"Thiacloprid","category":"Insecticides"},
{"ingredient":"Thidiazuron","category":"Plant Growth Regulators"},
{"ingredient":"Thiencarbazone-methyl","category":"Herbicides"},
{"ingredient":"Thiodicarb","category":"Insecticides"},
{"ingredient":"Thiodicarb","category":"Seed Treatment"},
{"ingredient":"Triadimefon","category":"Fungicides"},
{"ingredient":"Triadimenol","category":"Fungicides"},
{"ingredient":"Triadimenol","category":"Seed Treatment"},
{"ingredient":"Tribufos","category":"Plant Growth Regulators"},
{"ingredient":"Trifloxystrobin","category":"Fungicides"},
{"ingredient":"Trifloxystrobin","category":"Seed Treatment"},
{"ingredient":"Triflumuron","category":"Insecticides"}]}
