inputBrands = {"bayer":[
{"productName":"Act","productIngredient":"Mefenacet"},
{"productName":"Actril","productIngredient":"Ioxynil"},
{"productName":"Adengo (Corn)","productIngredient":"Thiencarbazone-methyl"},
{"productName":"Adengo","productIngredient":"Isoxaflutole"},
{"productName":"Admire","productIngredient":"Imidacloprid"},
{"productName":"Aeris","productIngredient":"Imidacloprid"},
{"productName":"Alanto","productIngredient":"Thiacloprid"},
{"productName":"Aliette","productIngredient":"Fosetyl-Al"},
{"productName":"Alion","productIngredient":"Indaziflam"},
{"productName":"Alister","productIngredient":"Diflufenican"},
{"productName":"Alister","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Alsystin","productIngredient":"Triflumuron"},
{"productName":"Amigo","productIngredient":"Imidacloprid"},
{"productName":"Amparo","productIngredient":"Imidacloprid"},
{"productName":"Ancla","productIngredient":"Imidacloprid"},
{"productName":"Antracol","productIngredient":"Propineb"},
{"productName":"Arcado","productIngredient":"Carpropamid"},
{"productName":"Archipel","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Arena C","productIngredient":"Tebuconazole"},
{"productName":"Arkan","productIngredient":"Amidosulfuron"},
{"productName":"Arozin","productIngredient":"Anilofos"},
{"productName":"Artemis","productIngredient":"Amidosulfuron"},
{"productName":"Artist","productIngredient":"Flufenacet"},
{"productName":"Asket","productIngredient":"Phenmedipham"},
{"productName":"Atento","productIngredient":"Fluquinconazole"},
{"productName":"Atlantis","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Attribut","productIngredient":"Propoxycarbazone-Sodium"},
{"productName":"Audax","productIngredient":"Imidacloprid"},
{"productName":"Autumn","productIngredient":"Iodosulfuron"},
{"productName":"Auxo","productIngredient":"Tembotrione"},
{"productName":"Aviator Xpro","productIngredient":"Bixafen "},
{"productName":"Axiom","productIngredient":"Flufenacet"},
{"productName":"Azur","productIngredient":"Diflufenican"},
{"productName":"Bacara","productIngredient":"Flurtamone "},
{"productName":"Baghera","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Balance","productIngredient":"Isoxaflutole"},
{"productName":"Bandur1","productIngredient":"Aclonifen"},
{"productName":"Bariard","productIngredient":"Thiacloprid"},
{"productName":"Bariton","productIngredient":"Fluoxastrobin"},
{"productName":"Basta","productIngredient":"Glufosinate-ammonium [non-selective usage]"},
{"productName":"Batl","productIngredient":"Mefenacet"},
{"productName":"Baycid","productIngredient":"Fenthion"},
{"productName":"Baycoral","productIngredient":"Bitertanol"},
{"productName":"Baycor","productIngredient":"Bitertanol"},
{"productName":"Bayfidan","productIngredient":"Triadimenol"},
{"productName":"Bayleton","productIngredient":"Triadimefon"},
{"productName":"Baysiston","productIngredient":"Triadimenol"},
{"productName":"Baytan","productIngredient":"Triadimenol"},
{"productName":"Baythroid XL","productIngredient":"Betacyfluthrin"},
{"productName":"Becano","productIngredient":"Indaziflam"},
{"productName":"Belt","productIngredient":"Flubendiamide"},
{"productName":"Betamix","productIngredient":"Desmedipham"},
{"productName":"Betanal AM 22","productIngredient":"Desmedipham"},
{"productName":"Betanal Quattro","productIngredient":"Ethofumesate"},
{"productName":"Betanal","productIngredient":"Phenmedipham"},
{"productName":"Betanalexpert/elite","productIngredient":"Ethofumesate"},
{"productName":"Betanex","productIngredient":"Desmedipham"},
{"productName":"Biscaya","productIngredient":"Thiacloprid"},
{"productName":"Blindage","productIngredient":"Imidacloprid"},
{"productName":"Boreal","productIngredient":"Isoxaflutole"},
{"productName":"Brodal","productIngredient":"Diflufenican"},
{"productName":"Bronate Advanced","productIngredient":"Bromoxynil"},
{"productName":"Buctril M","productIngredient":"Bromoxynil"},
{"productName":"Buctril","productIngredient":"Bromoxynil"},
{"productName":"Bulldock","productIngredient":"Betacyfluthrin"},
{"productName":"Bullstar","productIngredient":"Betacyfluthrin"},
{"productName":"Caddy","productIngredient":"Cyproconazole"},
{"productName":"CaddyArbo","productIngredient":"Cyproconazole"},
{"productName":"Cadou","productIngredient":"Flufenacet"},
{"productName":"CaLypso","productIngredient":"Thiacloprid"},
{"productName":"Camposan1","productIngredient":"Ethephon"},
{"productName":"Capture","productIngredient":"Diflufenican"},
{"productName":"Carat","productIngredient":"Flurtamone "},
{"productName":"Carioca","productIngredient":"Aclonifen"},
{"productName":"Carioca","productIngredient":"Oxadiargyl"},
{"productName":"Censor","productIngredient":"Fenamidone"},
{"productName":"Cerenturf","productIngredient":"Pencycuron"},
{"productName":"Cerone","productIngredient":"Ethephon"},
{"productName":"Certero","productIngredient":"Triflumuron"},
{"productName":"Certop","productIngredient":"Filmcoating"},
{"productName":"Challenge","productIngredient":"Aclonifen"},
{"productName":"Cheetah","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Chekker","productIngredient":"Iodosulfuron"},
{"productName":"Chevalier","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Chinook","productIngredient":"Imidacloprid"},
{"productName":"Clarinet","productIngredient":"Pyrimethanil"},
{"productName":"Confidor Energy","productIngredient":"Deltamethrin"},
{"productName":"Confidor O-teq","productIngredient":"Imidacloprid"},
{"productName":"Confidor","productIngredient":"Imidacloprid"},
{"productName":"Connect","productIngredient":"Betacyfluthrin"},
{"productName":"Connect","productIngredient":"Imidacloprid"},
{"productName":"Consento","productIngredient":"Fenamidone"},
{"productName":"Consento","productIngredient":"Propamocarb HCl"},
{"productName":"Corvus (Corn)","productIngredient":"Thiencarbazone-methyl"},
{"productName":"Corvus","productIngredient":"Isoxaflutole"},
{"productName":"Cossack","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Cougar","productIngredient":"Diflufenican"},
{"productName":"CropStar","productIngredient":"Imidacloprid"},
{"productName":"Curbix","productIngredient":"Ethiprole"},
{"productName":"Daniemon (in japanese characters)","productIngredient":"Spirodiclofen"},
{"productName":"Datif G","productIngredient":"Filmcoating"},
{"productName":"Decis","productIngredient":"Deltamethrin"},
{"productName":"Define","productIngredient":"Flufenacet"},
{"productName":"Def","productIngredient":"Tribufos"},
{"productName":"Delaro","productIngredient":"Trifloxystrobin"},
{"productName":"Delcut","productIngredient":"Oxadiazon"},
{"productName":"Derosal Plus","productIngredient":"Carbendazim"},
{"productName":"Derosal","productIngredient":"Carbendazim"},
{"productName":"Derosal","productIngredient":"Carbendazim"},
{"productName":"Diplome","productIngredient":"Metosulam"},
{"productName":"Dopler","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Doublestar","productIngredient":"Fentrazamide"},
{"productName":"Draza","productIngredient":"Methiocarb"},
{"productName":"Dropp Ultra1","productIngredient":"Thidiazuron"},
{"productName":"Dropp SC","productIngredient":"Thidiazuron"},
{"productName":"Dropp Ultra","productIngredient":"Thidiazuron"},
{"productName":"Dropp","productIngredient":"Thidiazuron"},
{"productName":"Eagle","productIngredient":"Amidosulfuron"},
{"productName":"Eclipse","productIngredient":"Metosulam"},
{"productName":"efa","productIngredient":"Fluoxastrobin"},
{"productName":"El Hombre","productIngredient":"Imidacloprid"},
{"productName":"Elite","productIngredient":"Tebuconazole"},
{"productName":"Envidor","productIngredient":"Spirodiclofen"},
{"productName":"Equip","productIngredient":"Foramsulfuron"},
{"productName":"Escocet","productIngredient":"Imidacloprid"},
{"productName":"Estalion","productIngredient":"Ethoxysulfuron"},
{"productName":"Ethrel","productIngredient":"Ethephon"},
{"productName":"Evidence","productIngredient":"Imidacloprid"},
{"productName":"Exact","productIngredient":"Triadimenol"},
{"productName":"Faibel","productIngredient":"Imidacloprid"},
{"productName":"Falcon","productIngredient":"Spiroxamine"},
{"productName":"Falcon","productIngredient":"Tebuconazole"},
{"productName":"Fandango","productIngredient":"Fluoxastrobin "},
{"productName":"FandangoS","productIngredient":"Fluoxastrobin "},
{"productName":"Fenikan","productIngredient":"Diflufenican"},
{"productName":"Fenix","productIngredient":"Aclonifen"},
{"productName":"Fenomenal","productIngredient":"Fenamidone"},
{"productName":"Finale","productIngredient":"Glufosinate-ammonium [non-selective usage]"},
{"productName":"Finish 6 Pro","productIngredient":"Ethephon"},
{"productName":"Finish","productIngredient":"Ethephon"},
{"productName":"First","productIngredient":"Diflufenican"},
{"productName":"Fitoraz","productIngredient":"Propineb"},
{"productName":"Flint","productIngredient":"Trifloxystrobin"},
{"productName":"Folicur","productIngredient":"Tebuconazole"},
{"productName":"Furore","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Futur","productIngredient":"Thiodicarb"},
{"productName":"Galahad","productIngredient":"Ethofumesate"},
{"productName":"Galmano Plus","productIngredient":"Fluquinconazole"},
{"productName":"Galmano","productIngredient":"Fluquinconazole"},
{"productName":"Gaucho MT","productIngredient":"Imidacloprid"},
{"productName":"Gaucho MZ","productIngredient":"Imidacloprid"},
{"productName":"Gaucho Primo","productIngredient":"Imidacloprid"},
{"productName":"Gaucho XT","productIngredient":"Imidacloprid"},
{"productName":"Gaucho","productIngredient":"Imidacloprid"},
{"productName":"Ginstar","productIngredient":"Thidiazuron"},
{"productName":"Gladium","productIngredient":"Ethoxysulfuron"},
{"productName":"Gratil","productIngredient":"Amidosulfuron"},
{"productName":"Grazie","productIngredient":"Ethoxysulfuron"},
{"productName":"Grodyl","productIngredient":"Amidosulfuron"},
{"productName":"Harpo Z","productIngredient":"Diflufenican"},
{"productName":"Herold","productIngredient":"Diflufenican"},
{"productName":"Hero","productIngredient":"Ethoxysulfuron"},
{"productName":"Hinochloa","productIngredient":"Mefenacet"},
{"productName":"Hoegrass","productIngredient":"Diclofop-methyl"},
{"productName":"Hoelon","productIngredient":"Diclofop-methyl"},
{"productName":"Hoestar","productIngredient":"Amidosulfuron"},
{"productName":"Horizon","productIngredient":"Tebuconazole"},
{"productName":"Huskie","productIngredient":"Pyrasulfotole"},
{"productName":"Hussar Evolution","productIngredient":"Iodosulfuron"},
{"productName":"Hussar maxx","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Hussar OF","productIngredient":"Iodosulfuron"},
{"productName":"Hussar","productIngredient":"Iodosulfuron"},
{"productName":"Huzar Activ","productIngredient":"Iodosulfuron"},
{"productName":"Illoxan","productIngredient":"Diclofop-methyl"},
{"productName":"Iloxan)","productIngredient":"Diclofop-methyl"},
{"productName":"Imochi Ace Kirappu","productIngredient":"Metominostrobin"},
{"productName":"Imochi Ace Starkle","productIngredient":"Metominostrobin"},
{"productName":"Imochi Ace","productIngredient":"Metominostrobin"},
{"productName":"Imprimo","productIngredient":"Imidacloprid"},
{"productName":"Impulse","productIngredient":"Spiroxamine"},
{"productName":"Infinito","productIngredient":"Fluopicolide"},
{"productName":"Infinito","productIngredient":"Propamocarb HCl"},
{"productName":"Infinity","productIngredient":"Pyrasulfotole"},
{"productName":"Innova DX","productIngredient":"Fentrazamide"},
{"productName":"Innova","productIngredient":"Fentrazamide"},
{"productName":"Input Set","productIngredient":"Spiroxamine"},
{"productName":"Input","productIngredient":"Prothioconazole "},
{"productName":"Invento","productIngredient":"Iprovalicarb"},
{"productName":"Jaunt","productIngredient":"Fluoxastrobin "},
{"productName":"Javelin","productIngredient":"Diflufenican"},
{"productName":"Jockey","productIngredient":"Fluquinconazole"},
{"productName":"Justmeet","productIngredient":"Fenhexamid"},
{"productName":"Kemifam Flow","productIngredient":"Phenmedipham"},
{"productName":"Kendo","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Kirappu","productIngredient":"Ethiprole"},
{"productName":"Lagon","productIngredient":"Isoxaflutole"},
{"productName":"Lamardor","productIngredient":"Prothioconazole"},
{"productName":"Larvin","productIngredient":"Thiodicarb"},
{"productName":"Laudis","productIngredient":"Tembotrione"},
{"productName":"Laureat","productIngredient":"Diflufenican"},
{"productName":"Lazulie","productIngredient":"Fenhexamid"},
{"productName":"Lebaycid","productIngredient":"Fenthion"},
{"productName":"Lecspro","productIngredient":"Fentrazamide"},
{"productName":"Lecs","productIngredient":"Fentrazamide"},
{"productName":"Legion","productIngredient":"Amidosulfuron"},
{"productName":"Leverage","productIngredient":"Betacyfluthrin"},
{"productName":"Liberator","productIngredient":"Flufenacet"},
{"productName":"Liberty","productIngredient":"Glufosinate-ammonium [selective usage]"},
{"productName":"Longshot","productIngredient":"Benfuresate"},
{"productName":"Longshot","productIngredient":"Oxadiazon"},
{"productName":"Madison","productIngredient":"Trifloxystrobin"},
{"productName":"Maedusi","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Magic Tandem","productIngredient":"Ethofumesate"},
{"productName":"Magma","productIngredient":"Mefenacet"},
{"productName":"MaisTer","productIngredient":"Foramsulfuron"},
{"productName":"Mandore","productIngredient":"Iprovalicarb"},
{"productName":"Matador","productIngredient":"Tebuconazole"},
{"productName":"Melody Care/Combi/Compact/Duo/Med/Trio","productIngredient":"Iprovalicarb"},
{"productName":"Merlin","productIngredient":"Isoxaflutole"},
{"productName":"Mesurol Pro","productIngredient":"Methiocarb"},
{"productName":"Mesurol","productIngredient":"Methiocarb"},
{"productName":"Mesurol","productIngredient":"Methiocarb"},
{"productName":"Mikado","productIngredient":"Sulcotrione"},
{"productName":"Mikal","productIngredient":"Fosetyl-Al"},
{"productName":"Mildex","productIngredient":"Fenamidone"},
{"productName":"Milord","productIngredient":"Spiroxamine"},
{"productName":"Milraz","productIngredient":"Propineb"},
{"productName":"Milrod","productIngredient":"Tebuconazole"},
{"productName":"Monarca","productIngredient":"Thiacloprid"},
{"productName":"Monceren Pro","productIngredient":"Pencycuron"},
{"productName":"Moncerenrunner","productIngredient":"Pencycuron"},
{"productName":"Monceren G","productIngredient":"Imidacloprid"},
{"productName":"Monceren GT","productIngredient":"Imidacloprid"},
{"productName":"Monceren","productIngredient":"Pencycuron"},
{"productName":"Monceren","productIngredient":"Pencycuron"},
{"productName":"Montur","productIngredient":"Imidacloprid"},
{"productName":"Movento","productIngredient":"Spirotetramat"},
{"productName":"Muralla","productIngredient":"Imidacloprid"},
{"productName":"Mythos","productIngredient":"Pyrimethanil"},
{"productName":"Nativo","productIngredient":"Tebuconazole"},
{"productName":"Nativo","productIngredient":"Trifloxystrobin"},
{"productName":"Nikeyl","productIngredient":"Aclonifen"},
{"productName":"Nominee","productIngredient":"Bispyribac-sodium"},
{"productName":"Nortron","productIngredient":"Ethofumesate"},
{"productName":"Oberon","productIngredient":"Spiromesifen"},
{"productName":"Ocarina","productIngredient":"Iprovalicarb"},
{"productName":"Octave","productIngredient":"Prochloraz"},
{"productName":"Odena","productIngredient":"Iprovalicarb"},
{"productName":"Olympus","productIngredient":"Propoxycarbazone-Sodium"},
{"productName":"OlympusFlex)","productIngredient":"Propoxycarbazone-Sodium"},
{"productName":"Omega","productIngredient":"Prochloraz"},
{"productName":"OnlyOne","productIngredient":"Tebuconazole"},
{"productName":"Option","productIngredient":"Foramsulfuron"},
{"productName":"Oribright","productIngredient":"Metominostrobin"},
{"productName":"Osprey","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Othello","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Oxytril","productIngredient":"Bromoxynil"},
{"productName":"Pacifica","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Panther","productIngredient":"Diflufenican"},
{"productName":"Pardner","productIngredient":"Bromoxynil"},
{"productName":"Password","productIngredient":"Fenhexamid"},
{"productName":"Peridiam","productIngredient":"Filmcoating"},
{"productName":"Podium S","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Poncho","productIngredient":"Clothianidin"},
{"productName":"PonchoBeta","productIngredient":"Clothianidin"},
{"productName":"PositronDuo","productIngredient":"Iprovalicarb"},
{"productName":"Precept and Wolverine","productIngredient":"Pyrasulfotole"},
{"productName":"Prep","productIngredient":"Ethephon"},
{"productName":"Prestige","productIngredient":"Imidacloprid"},
{"productName":"Prestige","productIngredient":"Pencycuron"},
{"productName":"Previcur N","productIngredient":"Propamocarb HCl"},
{"productName":"Previcur Energy","productIngredient":"Propamocarb HCl"},
{"productName":"Proclaim","productIngredient":"Bitertanol"},
{"productName":"Prodigio","productIngredient":"Aclonifen"},
{"productName":"Profiler","productIngredient":"Fluopicolide"},
{"productName":"Profiler","productIngredient":"Fosetyl-Al"},
{"productName":"Proline","productIngredient":"Prothioconazole "},
{"productName":"Pronto Plus","productIngredient":"Spiroxamine"},
{"productName":"ProntoPlus","productIngredient":"Tebuconazole"},
{"productName":"Prosaro","productIngredient":"Prothioconazole "},
{"productName":"Prosaro","productIngredient":"Tebuconazole"},
{"productName":"Proseed","productIngredient":"Prothioconazole"},
{"productName":"Prosper","productIngredient":"Clothianidin"},
{"productName":"Prosper","productIngredient":"Spiroxamine"},
{"productName":"Proteus","productIngredient":"Deltamethrin"},
{"productName":"Proteus","productIngredient":"Thiacloprid"},
{"productName":"Provado","productIngredient":"Imidacloprid"},
{"productName":"Provence","productIngredient":"Isoxaflutole"},
{"productName":"Provost","productIngredient":"Prothioconazole "},
{"productName":"Pulstop","productIngredient":"Fentrazamide"},
{"productName":"Puma Super","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Quartz GT","productIngredient":"Diflufenican"},
{"productName":"Quartz S","productIngredient":"Diflufenican"},
{"productName":"Quartz Super","productIngredient":"Diflufenican"},
{"productName":"R6 Albis","productIngredient":"Fosetyl-Al"},
{"productName":"R6 Trevi","productIngredient":"Fosetyl-Al"},
{"productName":"Radius","productIngredient":"Flufenacet"},
{"productName":"Raft","productIngredient":"Oxadiargyl"},
{"productName":"Ralon Super","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Rancho","productIngredient":"Mefenacet"},
{"productName":"Rasantan","productIngredient":"Amidosulfuron"},
{"productName":"Raxil Extra","productIngredient":"Tebuconazole"},
{"productName":"Raxil T","productIngredient":"Tebuconazole"},
{"productName":"Raxil","productIngredient":"Tebuconazole"},
{"productName":"Reason","productIngredient":"Fenamidone"},
{"productName":"Redigo","productIngredient":"Prothioconazole"},
{"productName":"Rely","productIngredient":"Glufosinate-ammonium [non-selective usage]"},
{"productName":"Revent","productIngredient":"Thidiazuron"},
{"productName":"Rhizofilm","productIngredient":"Filmcoating"},
{"productName":"Rhodax","productIngredient":"Fosetyl-Al"},
{"productName":"Ricestar Xtra","productIngredient":"Ethoxysulfuron"},
{"productName":"Ricestar","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Rimfire Max","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Ronstar D Flo","productIngredient":"Oxadiazon"},
{"productName":"Ronstar PL","productIngredient":"Oxadiazon"},
{"productName":"Ronstar","productIngredient":"Oxadiazon"},
{"productName":"Routine","productIngredient":"Isotianil"},
{"productName":"Rovral","productIngredient":"Iprodione"},
{"productName":"Rumpas","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Scala","productIngredient":"Pyrimethanil"},
{"productName":"Scenic","productIngredient":"Fluoxastrobin"},
{"productName":"Sekator","productIngredient":"Iodosulfuron"},
{"productName":"Semevin","productIngredient":"Thiodicarb"},
{"productName":"Sencoral‚ Sencorex","productIngredient":"Metribuzin"},
{"productName":"Sencor","productIngredient":"Metribuzin"},
{"productName":"Sevin XLR Plus","productIngredient":"Carbaryl"},
{"productName":"Sevin","productIngredient":"Carbaryl"},
{"productName":"Siganex","productIngredient":"Pyrimethanil"},
{"productName":"Sigma","productIngredient":"Mesosulfuron-methyl"},
{"productName":"Silvacur","productIngredient":"Tebuconazole"},
{"productName":"Sirbel","productIngredient":"Iprovalicarb"},
{"productName":"Skol","productIngredient":"Ethoxysulfuron"},
{"productName":"Skyway Xpro","productIngredient":"Bixafen "},
{"productName":"Soberan","productIngredient":"Tembotrione"},
{"productName":"Solomon","productIngredient":"Betacyfluthrin"},
{"productName":"Specticle","productIngredient":"Indaziflam"},
{"productName":"Sphere","productIngredient":"Trifloxystrobin"},
{"productName":"Sporgon","productIngredient":"Prochloraz"},
{"productName":"Sportak","productIngredient":"Prochloraz"},
{"productName":"Squire","productIngredient":"Amidosulfuron"},
{"productName":"Stallion","productIngredient":"Ethoxysulfuron"},
{"productName":"Stance SC","productIngredient":"Cyclanilide"},
{"productName":"Starice","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Stratego","productIngredient":"Trifloxystrobin"},
{"productName":"Sunrice","productIngredient":"Ethoxysulfuron"},
{"productName":"Sunstar","productIngredient":"Ethoxysulfuron"},
{"productName":"Tega","productIngredient":"Trifloxystrobin"},
{"productName":"Teldor Combi","productIngredient":"Fenhexamid"},
{"productName":"Teldor","productIngredient":"Fenhexamid"},
{"productName":"Terano","productIngredient":"Flufenacet"},
{"productName":"Terano","productIngredient":"Metosulam"},
{"productName":"Thumper","productIngredient":"Bromoxynil"},
{"productName":"Thunder O-teq","productIngredient":"Imidacloprid"},
{"productName":"Tiara","productIngredient":"Flufenacet"},
{"productName":"Tie Break","productIngredient":"Fenhexamid"},
{"productName":"Tigrex","productIngredient":"Diflufenican"},
{"productName":"Tihan (cotton in West Africa)","productIngredient":"Spirotetramat"},
{"productName":"Tiller Gold","productIngredient":"Ethoxysulfuron"},
{"productName":"Tiller","productIngredient":"Ethoxysulfuron"},
{"productName":"Tiller","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Tilmor","productIngredient":"Prothioconazole "},
{"productName":"Topstar","productIngredient":"Oxadiargyl"},
{"productName":"Totril","productIngredient":"Ioxynil"},
{"productName":"Tramat","productIngredient":"Ethofumesate"},
{"productName":"Trilex","productIngredient":"Trifloxystrobin"},
{"productName":"Trivia","productIngredient":"Fluopicolide"},
{"productName":"Trotis","productIngredient":"Pencycuron"},
{"productName":"Tundra","productIngredient":"Pyrasulfotole"},
{"productName":"Turbo","productIngredient":"Betacyfluthrin"},
{"productName":"Turbo","productIngredient":"Ethoxysulfuron"},
{"productName":"Turfsiba","productIngredient":"Pencycuron"},
{"productName":"Twist","productIngredient":"Trifloxystrobin"},
{"productName":"Ultari","productIngredient":"Pencycuron"},
{"productName":"Ultor (second market USA)","productIngredient":"Spirotetramat"},
{"productName":"Valiant","productIngredient":"Fosetyl-Al"},
{"productName":"Velocity M3","productIngredient":"Pyrasulfotole"},
{"productName":"Velocity (Cereals)","productIngredient":"Thiencarbazone-methyl"},
{"productName":"Velocity","productIngredient":"Pyrasulfotole"},
{"productName":"Verita","productIngredient":"Fenamidone"},
{"productName":"Vigold","productIngredient":"Fluoxastrobin "},
{"productName":"Vision","productIngredient":"Pyrimethanil"},
{"productName":"Volare","productIngredient":"Fluopicolide"},
{"productName":"Votivo; Poncho/Votivo","productIngredient":"Bacillus firmus"},
{"productName":"Walabi","productIngredient":"Pyrimethanil"},
{"productName":"Whip","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"Wildcat","productIngredient":"Fenoxaprop-P-ethyl"},
{"productName":"WinAdmire","productIngredient":"Carpropamid"},
{"productName":"WinAdmireGreatam","productIngredient":"Carpropamid"},
{"productName":"Win","productIngredient":"Carpropamid"},
{"productName":"WinBariard","productIngredient":"Carpropamid"},
{"productName":"WinGazzet","productIngredient":"Carpropamid"},
{"productName":"Wolface","productIngredient":"Mefenacet"},
{"productName":"Yorel","productIngredient":"Iprovalicarb"},
{"productName":"Yunta","productIngredient":"Imidacloprid"},
{"productName":"Zantara","productIngredient":"Bixafen "},
{"productName":"Zark","productIngredient":"Mefenacet"},
{"productName":"Zato","productIngredient":"Trifloxystrobin"},
{"productName":"ZorroFS 236,3","productIngredient":"Imidacloprid"},
{"productName":"Adret","productIngredient":"Amidosulfuron"},
{"productName":"Decision","productIngredient":"Diclofop-methyl"}]}

inputIngredients = {"Bayer":[
{"ingredient":"Aclonifen","category":"Herbicides"},
{"ingredient":"Amidosulfuron","category":"Herbicides"},
{"ingredient":"Anilofos","category":"Herbicides"},
{"ingredient":"Bacillus firmus","category":"Seed Treatment"},
{"ingredient":"Benfuresate","category":"Herbicides"},
{"ingredient":"Betacyfluthrin","category":"Insecticides"},
{"ingredient":"Bispyribac-sodium","category":"Herbicides"},
{"ingredient":"Bitertanol","category":"Fungicides"},
{"ingredient":"Bixafen ","category":"Fungicides"},
{"ingredient":"Bromoxynil","category":"Herbicides"},
{"ingredient":"Carbaryl","category":"Insecticides"},
{"ingredient":"Carbendazim","category":"Fungicides"},
{"ingredient":"Carbendazim","category":"Seed Treatment"},
{"ingredient":"Carpropamid","category":"Fungicides"},
{"ingredient":"Clothianidin","category":"Seed Treatment"},
{"ingredient":"Cyclanilide","category":"Plant Growth Regulators"},
{"ingredient":"Cyproconazole","category":"Fungicides"},
{"ingredient":"Deltamethrin","category":"Insecticides"},
{"ingredient":"Desmedipham","category":"Herbicides"},
{"ingredient":"Diclofop-methyl","category":"Herbicides"},
{"ingredient":"Diflufenican","category":"Herbicides"},
{"ingredient":"Ethephon","category":"Plant Growth Regulators"},
{"ingredient":"Ethiprole","category":"Insecticides"},
{"ingredient":"Ethofumesate","category":"Herbicides"},
{"ingredient":"Ethoxysulfuron","category":"Herbicides"},
{"ingredient":"Fenamidone","category":"Fungicides"},
{"ingredient":"Fenhexamid","category":"Fungicides"},
{"ingredient":"Fenoxaprop-P-ethyl","category":"Herbicides"},
{"ingredient":"Fenthion","category":"Insecticides"},
{"ingredient":"Fentrazamide","category":"Herbicides"},
{"ingredient":"Filmcoating","category":"Seed Treatment"},
{"ingredient":"Flubendiamide","category":"Insecticides"},
{"ingredient":"Flufenacet","category":"Herbicides"},
{"ingredient":"Fluopicolide","category":"Fungicides"},
{"ingredient":"Fluoxastrobin ","category":"Fungicides"},
{"ingredient":"Fluoxastrobin","category":"Seed Treatment"},
{"ingredient":"Fluquinconazole","category":"Seed Treatment"},
{"ingredient":"Flurtamone ","category":"Herbicides"},
{"ingredient":"Foramsulfuron","category":"Herbicides"},
{"ingredient":"Fosetyl-Al","category":"Fungicides"},
{"ingredient":"Glufosinate-ammonium [non-selective usage]","category":"Herbicides"},
{"ingredient":"Glufosinate-ammonium [selective usage]","category":"Herbicides"},
{"ingredient":"Imidacloprid","category":"Insecticides"},
{"ingredient":"Imidacloprid","category":"Seed Treatment"},
{"ingredient":"Indaziflam","category":"Herbicides"},
{"ingredient":"Iodosulfuron","category":"Herbicides"},
{"ingredient":"Ioxynil","category":"Herbicides"},
{"ingredient":"Iprodione","category":"Fungicides"},
{"ingredient":"Iprovalicarb","category":"Fungicides"},
{"ingredient":"Isotianil","category":"Fungicides"},
{"ingredient":"Isoxaflutole","category":"Herbicides"},
{"ingredient":"Mefenacet","category":"Herbicides"},
{"ingredient":"Mesosulfuron-methyl","category":"Herbicides"},
{"ingredient":"Methiocarb","category":"Insecticides"},
{"ingredient":"Methiocarb","category":"Seed Treatment"},
{"ingredient":"Metominostrobin","category":"Fungicides"},
{"ingredient":"Metosulam","category":"Herbicides"},
{"ingredient":"Metribuzin","category":"Herbicides"},
{"ingredient":"Oxadiargyl","category":"Herbicides"},
{"ingredient":"Oxadiazon","category":"Herbicides"},
{"ingredient":"Pencycuron","category":"Fungicides"},
{"ingredient":"Pencycuron","category":"Seed Treatment"},
{"ingredient":"Phenmedipham","category":"Herbicides"},
{"ingredient":"Prochloraz","category":"Fungicides"},
{"ingredient":"Propamocarb HCl","category":"Fungicides"},
{"ingredient":"Propineb","category":"Fungicides"},
{"ingredient":"Propoxycarbazone-Sodium","category":"Herbicides"},
{"ingredient":"Prothioconazole ","category":"Fungicides"},
{"ingredient":"Prothioconazole","category":"Seed Treatment"},
{"ingredient":"Pyrasulfotole","category":"Herbicides"},
{"ingredient":"Pyrimethanil","category":"Fungicides"},
{"ingredient":"Spirodiclofen","category":"Insecticides"},
{"ingredient":"Spiromesifen","category":"Insecticides"},
{"ingredient":"Spirotetramat","category":"Insecticides"},
{"ingredient":"Spiroxamine","category":"Fungicides"},
{"ingredient":"Sulcotrione","category":"Herbicides"},
{"ingredient":"Tebuconazole","category":"Fungicides"},
{"ingredient":"Tebuconazole","category":"Seed Treatment"},
{"ingredient":"Tembotrione","category":"Herbicides"},
{"ingredient":"Thiacloprid","category":"Insecticides"},
{"ingredient":"Thidiazuron","category":"Plant Growth Regulators"},
{"ingredient":"Thiencarbazone-methyl","category":"Herbicides"},
{"ingredient":"Thiodicarb","category":"Insecticides"},
{"ingredient":"Thiodicarb","category":"Seed Treatment"},
{"ingredient":"Triadimefon","category":"Fungicides"},
{"ingredient":"Triadimenol","category":"Fungicides"},
{"ingredient":"Triadimenol","category":"Seed Treatment"},
{"ingredient":"Tribufos","category":"Plant Growth Regulators"},
{"ingredient":"Trifloxystrobin","category":"Fungicides"},
{"ingredient":"Trifloxystrobin","category":"Seed Treatment"},
{"ingredient":"Triflumuron","category":"Insecticides"}]}


#Monsanto brands
#<li><a href="/products/Pages/aquamaster-herbicide.aspx">AquaMaster</a></li><li><a href="http://www.monsanto.com/products/Pages/asgrow-soybeans.aspx">Asgrow</a></li><li><a href="/products/Pages/bullet-herbicide-acetanilide.aspx">Bullet</a></li><li><a href="/products/Pages/certainty-turf-herbicide.aspx">Certainty Turf</a></li><li><a href="http://www.monsanto.com/products/Pages/channel.aspx">Channel</a></li><li><a href="/products/Pages/degree-herbicide-acetanilide.aspx">Degree XTRA</a></li><li><a href="http://www.monsanto.com/products/Pages/dekalb.aspx  ">DEKALB</a></li><li><a href="http://www.monsanto.com/products/Pages/deltapine.aspx ">Deltapine</a></li><li><a href="http://www.monsanto.com/products/Pages/fielders-choice-direct.aspx ">Fielder's Choice Direct</a></li><li><a href="http://www.monsanto.com/products/Pages/fontanelle.aspx ">Fontanelle</a></li><li><a href="http://www.monsanto.com/products/Pages/gold-country-seed.aspx ">Gold Country Seed</a></li><li><a href="http://www.monsanto.com/products/Pages/hubner-seed.aspx ">Hubner Seed</a></li><li><a href="/products/Pages/intrro-acetanilide.aspx">INTRRO</a></li><li><a href="http://www.monsanto.com/products/Pages/jung-seed-genetics.aspx ">Jung Seed Genetics</a></li><li><a href="http://www.monsanto.com/products/Pages/kruger-seeds.aspx">Kruger Seeds</a></li><li><a href="/products/Pages/lariat-herbicide-acetanilide.aspx">Lariat</a></li><li><a href="http://www.monsanto.com/products/Pages/lewis-hybrids.aspx ">Lewis Hybrids</a></li><li><a href="/products/Pages/micro-tech-herbicide-acetanilide.aspx">Micro-Tech</a></li><li><a href="/products/Pages/outrider-herbicide.aspx">Outrider</a></li><li><a href="http://www.monsanto.com/products/Pages/rea-hybrids.aspx">Rea Hybrids</a></li><li><a href="/products/Pages/roundup-powermax-herbicide.aspx">Roundup PowerMAX</a></li><li><a href="/products/Pages/roundup-pro-concentrate.aspx">Roundup PRO Concentrate</a></li><li><a href="/products/Pages/roundup-promax.aspx">Roundup PROMAX</a></li><li><a href="/products/Pages/quikpro-herbicide.aspx">Roundup QuikPRO</a></li><li><a href="/products/Pages/roundup-weathermax-herbicide.aspx">Roundup WeatherMAX</a></li><li><a href="/products/Pages/RT3-herbicide.aspx">RT 3</a></li><li><a href="http://www.monsanto.com/products/Pages/specialty-hybrids.aspx ">Specialty Hybrids</a></li><li><a href="/products/Pages/stewart-seeds.aspx">Stewart Seeds</a></li><li><a href="http://www.monsanto.com/products/Pages/stone-seed-group.aspx">Stone Seed Group</a></li><li><a href="http://www.monsanto.com/products/Pages/trelay-seeds.aspx">Trelay Seeds</a></li><li><a href="http://www.monsanto.com/products/Pages/tripleflex-herbicide-acetochlor.aspx">TripleFLEX</a></li><li><a href="/products/Pages/westbred.aspx">WestBred</a></li>

