* SMS Examples

** Shorthand
#+BEGIN_QUOTE
s: stands for "scsms sends sms" [scsms stands for SMART Coops sms server]
f: stands for "farmer sends sms"
[some comment]: helpful comments to understand the dynamics
"*": wild card meaning "user sends some content, or no content at all, which is not a command recognized scsms"
#+END_QUOTE

** Firt time sign up, ask for name
[SMART_Coops.number = +63 151 888 4444]

f: "*" [farmer sends an SMS to +63 151 888 4444 with no intelligible content (for the first time)]
s: "Hello, I notice that it is the first time you are using SMART Coops. Please reply to SMS with your family name and given name (ex: Capitan, Sergio)."
f: "Gutierrez, Ramon"
s: "Pleased to meet you Mr. Ramon Gutierrez. Did I get your name correctly? (you can reply yes or no). Note that SMS sent to SMART Coops are free of charge, so do not worry about your account balance."
f: "yes"

** First time sign up, ask for Coop name
[Assuming it is the same number for all cooperatives in the Philipines]
s: "Great, thank you for confirming your name. SMART Coop helps find out about prices for crop inputs, crop produce, loans, and more. I see that you are sending me messages from near San Pablo, Languna. Which cooperative are you a member of? Type the corresponding number. 1) San Benito Multi Purpose Cooperative, 2) San Pablo Cooperative, 3) Los Banos Cooperative, 4) Other, 5) I am not a member of a cooperative"
f: "Other"
s: "What region is your farm located in? 1) Lauzon, 2) Visayas, 3) Mindanao"
f: "Lauzon"
s: "What provide inside Lauzon? 1) Bicol, 2) Laguna, 3) ..."
f: "2"
s: "You are in Laguna. Which city/baranguay is closest to you? If you make a typo, do not worry we will try to find the correct one" [substring search with closest match list return]
f: "Naga"
s: "Dear Mr. Ramon Gutierrez, I now understand that you own a farm near Naga City in Bicol. Which cooperative are you member of? 1) XXX, 2) YYY, 3) ZZZ"

** Ask for the crops
[Assuming the system now knows the name of the farmer and the cooperative he/she is a member of]
f: "*"
s: "Welcome back to SMART Coops. What crops, produce are you currently growing? 1) Rice, 2) Mango, 3) Pineapple, 4) Banana, 5) Coconut, 6) Other (you can also just name them)"
f: "Papayas, eggs, tilapia"
s: "I see that you are growing papayas, eggs, and tilapia. How many hectares of papayas have you planted? (ex: 1.5 hectares)"
f: "1.5"
s: "You are growing 1.5 hectares of papayas. What is your daily production of eggs? (ex: 1000 eggs)"
f: "papayas"
s: "Would you like to update the number of hectares of papayas that you cultivate? If yes, just enter the number"
f: "2.5"
s: "You are growing 2.5 hectares of papayas. What is your daily production of eggs? (ex: 1000 eggs)"
f: "Mangoes 1 hectare"
s: "You are growing 2.5 hectares of papayas, 1 hectare of mangoes. What is your daily product of eggs?  (ex: 1000 eggs)"
f: "1500"
s: "You are growing 2.5 hectares of papayas, 1 hectare of mangoes, and have a daily production of 1000 eggs. How many kilos of fish do you produce per week (ex: 10 kilograms)"
f: "20"
s: "You are growing 2.5 hectares of papayas, 1 hectare of mangoes, and have a daily production of 1000 eggs, and 20 kilograms of tilapia. Do you grow any other product?"
[User does not reply. The scsms will wait 24 hours and send the user a new question]

** Farmer is registered to SMART Coop, applies for a loan (Name, Coop, Crops)
[Assuming the system now knows the name of the farmer and the cooperative, and the production of the farmer]
f: "*"
s: "Hello! How many SMART Coops help you today? 1) Loan, 2) Buy inputs, 3) Sell produce, 4) Harvesting education, 5) View my profile, 6) Send SMART Coops a message"
f: "1"
s: "Loan menu. You currently do not have a loan. Would you like to apply for a loan? (yes or no)"
f: "Yes"
s: "We need to determine your loan eligibility amount. Your profile indicates that you are growing 2.5 hectares of papayas, 1 hectare of mangoes, and have a daily production of 1000 eggs, and 20 kilograms of tilapia. Do you grow any other product? (Yes or No)?"
f: "No"
s: "Based on the size of your production, you are eligible for a loan of approximately PHP 34,000. The coop is offering this loan at a 16% interest rate, payable in kind. How much would you like to apply for?"
f: "20,000"
s: "20,000 is the amount I received. The {{loan officer name}} of the {{coop name}} will be notified of your application. To change your loan application value, please go back to the loan menu"

** Farmer is registered to SMART Coop, receives a notification of loan approval (Name, Coop, Crops)
[Assuming the system now knows the name of the farmer and the cooperative, and the production of the farmer]
s: "Hello! SMART Coop would like to inform you that your 20,000 loan has been approved. The amount will be deposited in your bank account, and a P1500 will be available through your mobile money account starting next week. How many SMART Coops help you today? 1) Loan, 2) Buy inputs, 3) Sell produce, 4) Harvesting education, 5) Settings, 6) Send SMART Coops a message"
f: "1"
s: "Loan menu. You have been approved for a P20,000 loan. You do not have any loan outstanding and no further action is available at this time. How many SMART Coops help you today? 1) Loan, 2) Buy inputs, 3) Sell produce, 4) Harvesting education, 5) Settings, 6) Send SMART Coops a message"

** Farmer is registered to SMART Coop, buys inputs (Name, Coop, Crops)
[Assuming the system now knows the name of the farmer and the cooperative, and the production of the farmer]
[scsmss will use the farmer profile to determine menu options]
f: "*"
s: "Hello! How many SMART Coops help you today? 1) Loan, 2) Buy inputs, 3) Sell produce, 4) Harvesting education, 5) Update farm profile, 6) Send SMART Coops a message"
f: "2"
s: "Buy inputs menu. You currently have P19,000 in your electronic account. What category of product are you looking for? 1) General products, 2) Papayas inputs, 3) Mangoes inputs, 4) Eggs inputs, 5) Tilapia inputs, 6) Back to main menu"
f: "1"
s: "Buy inputs, general products menu. Current market price for gasolina is P45/litre and LPG P344/tank. Would you like to play an order for: 1) Gasolina, 2) LPG, 3) Back to inputs menu, 4) Back to main menu.
f: "1"
s: "Buy inputs, general products gasolina menu. How many litres of gasolina would you like to purchase? (ex: 34)"
f: "10"
s: "You are about to purchase 10 litres for a total of P450, which will be devited from your account which currently holds P19,000. Reply 'yes' to confirm or 'no' to cancel"
f: "Yes"
s: "Excellent. The purchase order has been sent to {{coop sales}}. Once the transaction is confirmed, your account will be debited by that amount. What category of product are you looking for? 1) General products, 2) Papayas inputs, 3) Mangoes inputs, 4) Eggs inputs, 5) Tilapia inputs, 6) Back to main menu"
f: "2"
s: "Buy inputs, papayas input. What inputs are you interested in? 1) Crop medicine, 2) Fertilizer, 3) Seeds"
f: "1"
s: "Buy inputs, papayas crop medicine menu. What crop medicine are you intersted in? 1) 2-4-D (weed killer), 2) Rogue (herbicide), 3) Puridan (insecticide), 4) Cynbus (insecticide), 5) Visokill (insecticide), 6) back to input menu, 7) Back to main menu"
f: "7"
s: "Hello! How many SMART Coops help you today? 1) Loan, 2) Buy inputs, 3) Sell produce, 4) Harvesting education, 5) Update farm profile, 6) Send SMART Coops a message"
f: "2"
s: "Buy inputs menu. You currently have P19,000 in your electronic account. What category of product are you looking for? 1) General products, 2) Papayas inputs, 3) Mangoes inputs, 4) Eggs inputs, 5) Tilapia inputs, 6) Back to main menu"
f: "3"
s: "Buy inputs, mangoes inputs. What inputs are you interested in? 1) Crop medicine, 2) Fertilizer, 3) Seeds, 4) back to input menu, 5) Back to main menu"
f: "2"
s: "Buy inputs, mangoes fertilizer menu. What are you intersted in? 1) Organic fertilizer, 2) Triple 14 (fertilizer), 3) back to input menu, 5) Back to main menu"

** Farmer is registered to SMART Coop, buys inputs (Name, Coop, Crops)
[Assuming the system now knows the name of the farmer and the cooperative, and the production of the farmer]
[scsmss will use the farmer profile to determine menu options]
f: "*"
s: "Hello! How many SMART Coops help you today? 1) Loan, 2) Buy inputs, 3) Sell produce, 4) Harvesting education, 5) Update farm profile, 6) Send SMART Coops a message"
f: "3"
s: "Your profile indicates that you are growing 2.5 hectares of papayas, 1 hectare of mangoes, and have a daily production of 1000 eggs, and 20 kilograms of tilapia. What produce are you interested in selling? 1) papayas, 2) mangoes, 3) eggs, 4) tilapia"
[not finished]




language computer shootout

travis-ci.org
sphinx.pocoo.org host on readthedocs.com
philweavers
github.com/edu
bryanveloso

* Daily financial transactions

These are operations done by the Coops, not by the farmer. The information listed below is the same level of information that the Coop uses everyday. The San Benito Multipurpose Coop uses the terms "products" for crop inputs, and "articles" for produce. 

** Product Charge Invoice

*** Description
when farmers borrow in kind from the cooperative; "pautang" of supplies; crop inputs or supplies such as LPG

*** Fields
- Date (of transaction)
- Sold to (Customer/Farmer)
- For each product sold
  -- Description (Name of product or supply)
  -- Quantity (of each product or supply)
  -- Unit price (of each product or supply)
  -- Amount (Quantity * Unit Price)
- Total Amount (Sum of Amounts for each product ordered)

*** Sample SMS Format
CHARGE Customer/Description/Quantity/Unit Price
Examples:
charge charlie santos/24D/2/25
ChArGe ChArLiE SaNTos/viking/3/100
charge charlie santos/viking/3/100/24D/2/25

** Article Delivery Receipt

*** Description
when the coop delivers rice to market or a creditor; eg. Coop delivers rice to UP Los Baños; "deliver" does not always mean that the coop takes care of the transportation, it might also mean a pickup

*** Fields
- Delivery Receipt (Date of delivery)
- Delivered to (Name of person/company that receives)
- For each article sold
  -- Articles (Description of product and quantity, eg. SKS Rice, NSIS - 30; Less VAT or Value Added Tax)
  -- Unit price
  -- Amount (Quantity * Unit Price)
- Total Amount (Sum of Amounts for each article ordered)

*** Sample SMS Format
DELIVERY Name/Articles/Quantity/Unit Price
Examples:
delivery UPLB/SKS Rice/3/1000
delivery UPLB/SKS Rice/3/1000/NSIS/30/1000

** Official Receipt (OR)

*** Description
used for cash transactions only such as when a farmer pays his debts; in more complicated circumstances, it can also be tied in with a delivery receipt but for the purpose of the pilot, treat only as any cash transaction

*** Fields
- Date (of transaction)
- Received from (Name of payer)
- Particulars (Description of payment, eg. payment for rice)
- Amount
- Total (of all particulars)

*** Sample SMS Format
OR Received from/Particulars/Amount
Examples:
or Charlie Santos/payment for rice/10000
or Charlie Santos/payment for fuel/300/pinapple seeds/1500/24D/400

** Cash Voucher

*** Description
when the coop disburses cash loans to member farmers; also used for when they incur expenses, eg. Xerox Php14.00

*** Fields
- Date
- Name
- Description (pre-filled in the voucher with "Amount payable", "Gasoline and oil", etc. but any will do)
- Amount
- Explanation (a more detailed description but can be combined with "Description")

*** Sample SMS Format
CASHVOUCHER Name/Description/Amount
Examples:
cashvoucher Charlie Santos/loan/20000
cashvoucher Onyo Aquino/xerox/14 [in this case, Onyo is the coop officer who used his personal money to buy a xerox and then got reimbursed by the coop]

** Commodity Slip

*** Description
when farmers pay in kind such as bringing their rice sacks to pay for their loan

*** Fields
- Date
- Received from (Name of farmer)
- Description (Name of rice, eg. MS-6)
- Quantity Bags (bags of rice)
- Quantity Kilos (total kilos per type of rice brought in)
- Unit Price (per kilo of type of rice)
- MC (moisture content as determined by coop, may not be as important as a financial transaction)
- Remarks (Price set = Bags * Kilos * Unit Price)
- Total Amount

*** Sample Format
COMMODITY Name/Description/Bags/Kilos/Unit Price
Examples:
commodity Charlie Santos/MS6/4/200/15/ [4 bags for a total of 200kilos, at 15PHP for each kilo]

** Stock cards

*** Description
are used for tracking inventory, eg. fertilizer, rat poison, LPG; there are currently around 30 types of inventory kept by the coop

*** Fields
- Date
- Name of Product (eg. Granaxone, 24D)
- Received (when inventory is received from Supplier) or Sold (either for credit or purchase)
- Purchaser (can also be the supplier but the coop does not currently keep track of supplier)
- Invoice number
- Quantity (Unit is inferred from type of stock)
- Stock on Hand (less or plus every purchase or receipt of inventory)

*** Fields
REC Product/Invoice Number/Quantity/Stock on Hand
Examples:
REC granaxone/

SOLD Product/Inventory Number/Quantity/Stock on Hand
Examples:


** Ledger
*** Description
where the accounts of each member is kept; data is manually transferred from the different types of invoices; essentially, this is would be the report that will be generated based on the transactions above except for the Stock Cards
*** Fields
- Date
- Particulars (Description)
- Reference number (Receipt or Invoice number)
- Production Loan
 - Unit Price
 - Amount
 - Payment
- Rice
 - Unit price
 - Amount
 - Payment
- Interest
 - Loan Amount * number of days / 360 days * percentage interest
 - eg. 10000 (loan amount) * 180 / 360 * 22% = 1,100 (interest) making the amount payable after 180 days at PhP 11,100
- Balance (Loan amount - Payment (either in kind or cash))
